dist: xenial
language: python
python:
- '3.8'
- '3.9'
before_install:
- pip install poetry
install:
- poetry install -v
script:
- poetry run pylint ninjavis
- poetry run mypy ninjavis
deploy:
  provider: script
  script: poetry publish --build
  skip_existing: true
  on:
    tags: true
    branch: main
env:
  global:
  - secure: mYX813z6kURtqP6DrR19khqkFeqxcXz8o7jqCS5Weecw2VuHdlSO4P0QGJD3KwqDXsOtx4TftE2D1cevcTu4UrZijJVmFZKZOYGxuYyCzjy2E4CfXw5HsQmahGDmpud4hPZlMLCK9lgT1Bif7YEGG7w0i/4YhBUYNyLUageKTTTpuCNgcSx+IfczDqoDNSLgmrYcnm/c6VFVa8M9AEpY5MAvHZILrz/JPY/+h68O2G8mkDFW1DNBth9Sfh/214TSUyscivl8IB5mo6YHYB0U7f4nmR3zY0YlWYL5Rls7nPfN6jyBYYowiICm1OSGVtcUlQyzy4hFMfqMUkLPrh+E7aSxOgze0dW0UC8WbPUFb6gSRSAjuKIwY8gpECouGWvdBl8Mp7+9aZtN8OVT3jAg+FpxL6VyqNgPahhW8KuAFxn3qbKr4Jwp0oHx3s+RTEnQKbSLB2qg3OErS1uCOaSM+T5i5tVFJ7+IwbWLYjgmkJpL0NybRTopj+g/Plf4UjyJpFVDiyzpFCl/TDV1ofLxi5SIvfbyc5EiMoBNhyhIyIwvxHJgvrDbvAuK2p5lINax28c0LJoFAkqfDr7PokaSLy93Bnl/plUlN3a7PCAMVZCHEKX3rmsnGCR4yt1tncrFiRqeDaFXGRoN0g+GGkbBW34ZwGQoOIuidJ2cjiLhYic=
